spring:
    datasource:
        url: jdbc:mysql://localhost:3306/itsnow?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600
    
server:
    port: 8964

mybatis:
    basepackage: com.itsnow.user.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8961/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

logging:
    level:
        tk.mybatis: DEBUG
        com.itsnow.user: DEBUG
    config: classpath:logback.xml
    path: /itsnow/user

swagger:
    basepackage: com.itsnow.user.controller
    service:
        name: itsnow-user
        description: itsnow-user后端服务接口
        developer: topslee